spring:
  profiles:
    active: dev
  application:
    name: customer-service
    
server:
  port: 8081
  
feign:
  client: 
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: false
    
db:
  dbName: LocalCustomerDB
  dbUser: C:\etc\customer-secret-volume\customerUser
  dbPassword: C:\etc\customer-secret-volume\customerPass
  
order:
  host: localhost
  port: 8080
  relPath: /order
