apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  order-database-password: MTIzNDU2
  order-database-user: cGlvdHI=
  customer-database-password: MTIzNDU2
  customer-database-user: cGlvdHI=